### ISSUE TITLE
Statement is not `Send`

### ISSUE THREAD

**Issue by agalakhov** [steffengy/tiberius#26]
Despite the use of Arc, the Statement struct cannot be sent between threads as it uses RefCell twice:

the trait bound `std::cell::RefCell<std::option::Option<std::sync::Arc<tiberius::tokens::TokenColMetaData>>>: std::marker::Sync` is not satisfied in `tiberius::stmt::StatementInner`

the trait bound `std::cell::RefCell<std::option::Option<tiberius::stmt::StatementHandle>>: std::marker::Sync` is not satisfied in `tiberius::stmt::StatementInner`

**Comment by steffengy** [comment]
Let me know, if there are any further issues.
(Statement wasn't the only struct that was affected)

**Comment by agalakhov** [comment]
Thank you! Does it work properly if the same statement is used on different connections (probably in the same thread)?

**Comment by steffengy** [comment]
It won't work for different connections in all cases right now.
That's still something I'll need to look into, before releasing a new version.

**Comment by agalakhov** [comment]
I wonder how it could be reflected in the API. Right now I don't use prepared statements at all since I run multiple concurrent connections (in the same thread).

BTW, I'd like to have my connection back in case of SQL syntax error or other SQL runtime error. Right now it is only returned in Ok().

**Comment by steffengy** [comment]
It won't be any different in case of the API, just different internals binding a handle to a connection.

**Comment by agalakhov** [comment]
Do you mean binding to multiple connections at once?

**Comment by steffengy** [comment]
@agalakhov 
It's implemented in: eb20ac342b64f8f83924b9b1877c2b7229904a8d 
Feel free to test!

> Do you mean binding to multiple connections at once?

Prepared statements work lazily in tiberius.
If you prepare a statement, it actually does nothing.
On execution, it checks if a statement is prepared for that connection with the given query parameters.
If so, it reuses that handle, if not it does the acutal preparation (or a prepare_exec as an optimization, to be specific).

(If you pass a VARCHAR(10) as argument and one time an INT, tiberius needs to use different prepared statements under the hood, since the parameter types need to be specified when preparing)

So concluded: You can use statements across connections, threads, ... and tiberius will handle the preparation magically for you.

**Comment by agalakhov** [comment]
Thank you!
What I actually mean: if I do
```
let s1: Statement = s.clone();
let s2: Statement = s.clone();
conn1.query(s1, ...);
conn2.query(s2, ...);
```
I expect it to work.

**Comment by steffengy** [comment]
Yeah sure. A statement is nothing connection-specific.
On execution it will check what needs to be prepared/used in the background, without
you needing to intervene, as expected.

So yeah, your example should work.
