### ISSUE TITLE
assertion fails @ mods.rs:256

### ISSUE THREAD

**Issue by srpelissier** [steffengy/tiberius#3]
Hello. I'm pretty new to this. And trying to use rust to target a MSSQL database. And later replacing my usual tools with rust tools for automating tests, etc.
So I really appreciate if you can shed some light on the following error. Maybe is my code not good, maybe is it something else.

I make a connection to a database, then a query, then an assertion. The connection seems to work, but the query (a select \* from a single table) fails because of the `assertion at line 256 in mods.rs` where left gets 1452 bytes and right gets 4088 bytes.
My interpretation is the size of the packet does not match that which is advertised in the header. I honestly don't know what to do with that.

When I comment this line, then I get `ProtocolError(InvalidValue("header: unknown packet type 50", 0)), ..src/libcore/result.rs:788`.

The database in question is running on Microsoft SQL Server 2014. (MDAC 10.0.10586.0).

Thank you.

**Comment by srpelissier** [comment]
`cargo test` fails too, but due to a connection error as I believe it expects a locally running MSSQL Server instance.

**Comment by steffengy** [comment]
your interpretation is pretty much correct.
that's also why you get the ProtocolError, since the client does not seem to support what
the server is (trying) to do (whatever that may be).

A `SELECT *` should work and is also in the tests, what columns & types does the table have?
(It might be related to unsupported datatypes, but I don't quite grasp what could be going on there)

Also, yes, `cargo test` is run against a local server.

Let me know if you can provide an SQL schema, to reproduce

**Comment by srpelissier** [comment]
```
[dbo].[TBLCLIENT]
person_id: PK, FK, int, not null
client_category_id: FK, int, null
housingtype_id: FK, int, null
clientlockedtype_id: FK, int, null
client_number: nvarchar(12), not null
client_place_of_birth: nvarchar(80), null
client_data_of_death: datetime, null
client_locked_from: datetime, null
client_created_on: datetime, not null
client_modified_on: datetime, not null
client_is_of_multiple_birth: bit, null
```

**Comment by steffengy** [comment]
how many rows does your test setup have?

**Comment by srpelissier** [comment]
about 1813.

**Comment by steffengy** [comment]
ok maybe related to that, since I never tested with really big datasets.
I'll do some testing later and get back to you
