### ISSUE TITLE
No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by no23** [steffengy/tiberius#4]
Not sure if this project is still active or not, but using the newest version of Tiberius I only get "No connection could be made because the target machine actively refused it.". I have tried multiple connection strings to various hosts but still cannot get anything but that. 

The full error message:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 10061, message: "No connection could be made because the target machine actively refused it." } })', ../src/libcore\result.rs:788

My connection function:
`pub fn connection<'a>() -> Connection<'a, Box<TargetStream>>
{
    let opts = "server=127.0.0.1:1433;Database=DebugData;UID=DebugApp;PWD=!debugPwd1;";
    return Connection::connect(opts).unwrap();
}`

**Comment by steffengy** [comment]
TCP connections are disabled in the default MSSQL configuration, so that's likely the issue in your case, since support for Named Pipes/Shared Memory isn't implemented yet.

Generally I'm working on a rewrite, so I wouldn't advise to use this in anything remotely production relevant, since it's likely to fail in one or another way or to break at a later stage.

**Comment by no23** [comment]
I have named pipes and TCP connections enabled. I had to for another project I am working on. I was just trying to get it to work, I am new to rust and was just testing out some SQL frameworks. I already had an MS SQL server up and running so I thought I would try out this. Thanks for the reply though. I'll keep trying things.

**Comment by steffengy** [comment]
Maybe TCP only listens on a sepcific interface or on a port different than the standard port?

The error (WSAECONNREFUSED) is thrown by the windows networking layer, 
so it's really nothing library specific.
It simply means it tried to connect on the default port (1433) and "nothing answered".

**Comment by gugi9000** [comment]
Uhm. 
If it's a remote server (given the port forward) and a connection string that contains "server=127.0.0.1:1433", I'd think you need to change your connection string.

**Comment by gugi9000** [comment]
I had a chance to test it at work today. 

Both local and remote connections work fine, but if you need to supply an instance - *like with SQLExpress* - you get refused connection. And it looks like there is currently no way to indicate this with Tiberius. Yet.

**Comment by no23** [comment]
Thank you for looking in to this more. Today is the first day I have been able to look at it. I am fairly sure my connection string wasn't to 127.0.0.1. I'll have to take a look at that. Maybe I was setting the connection string wrong. I am currently using SQL server 2014 standard, on Windows server 2008. I will take a look at it later today and see what I can find.

**Comment by gugi9000** [comment]
@no23: Turns out, that you can connect to a SQLEXPRESS instance. You just have to locate the dynamic port.

In SQL Server Configuration Manager go to `SQL Server Network Configuration` -> `Protocols for SQLEXPRESS` -> `TCP/IP`. On the tab called IP Addresses under IPAll you will find the `TCP Dynamic Ports` field:

![billede](https://cloud.githubusercontent.com/assets/271348/22946753/9d65d954-f2f8-11e6-9305-58520a982284.png)

In this case making the connection string:
`let connect_string = "Server=tcp:localhost,49800;integratedSecurity=true;Database=FOO;".to_owned():`

I hope that helps :-)
