### ISSUE TITLE
Is datetime unimplemented at the moment?

### ISSUE THREAD

**Issue by madmaxio** [steffengy/tiberius#54]
Getting some issues with datetime, is I understand correctly sql server datetime type is not yet implemented in queries?

**Comment by steffengy** [comment]
datetime is implemented (as indicated in the README), what are the issues you're running into?

**Comment by madmaxio** [comment]
Datetime works, sorry, but i got panic from  

VarLenType::Daten => 3,
_ => unimplemented!(),


but can't reproduce it now, If I understand correctly it happens when type len is incorrect?

**Comment by steffengy** [comment]
That happens when a specific variable-length type is not supported.
SQLServer distinguishes between fixed length types that always have the same type and variable length types [which are most] which have to communicate how long the value is

Let me know when you can reproduce, because the only way to preemptively fix that,
would be to implement all remaining unimplemented types, which is a lot of work.
