### ISSUE TITLE
Connection pooling: not Send-able on "old"; is "master" usable?

### ISSUE THREAD

**Issue by ms705** [steffengy/tiberius#9]
Hi!

This is an awesome library -- thanks for writing it!

I've been looking at writing the necessary code to enable tiberius to be used within an [`r2d2`](https://github.com/sfackler/r2d2) connection pool, but I'm hitting a roadblock with the `old` branch: because `Connection` is not `Send` (due to `TargetStream`, I think), I cannot share a connection between threads via the pool.

I noticed that the `master` branch seems to add support for this kind of thing (via `tokio`); however, it doesn't currently pass the tests for me (due to "`unknown config option: \"integratedsecurity\"")'`"). Is `master` at all worth looking at, or is it too unstable to use at this point?

Thanks!

**Comment by steffengy** [comment]
master is pretty unstable right now but at a stage where it's already more stable
than old ever was.

The error you see is probably because you're running linux?
On windows the tests simply connect to the local machine using the current user 
(integrated windows authentication).
On linux that won't work and you'll have to overwrite the connection string
with the ```TIBERIUS_TEST_CONNECTION_STRING``` environment variable,
as we do for [travis](https://github.com/steffengy/tiberius/blob/master/.travis.yml#L9)

**Comment by ms705** [comment]
Great, thanks -- I'll use `master` then.

And indeed, tests pass if I override the `TIBERIUS_TEST_CONNECTION_STRING` variable as necessary. (I note that it's not currently possible to choose a non-default database context via the connection string any more; see #10.)
